#!/usr/bin/env bash
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"

MODE="${1:---files-only}"
LOCAL_HOSTNAME="${SM_LOCAL_HOSTNAME:-smartest.localhost}"
REWRITE_BASE="${SM_REWRITE_BASE:-/}"

DB_HOST="${SM_DB_HOST:-127.0.0.1}"
DB_NAME="${SM_DB_NAME:-smartest_php8}"
DB_USER="${SM_DB_USER:-smartest}"
DB_PASSWORD="${SM_DB_PASSWORD:-smartest}"

ADMIN_USER="${MYSQL_ADMIN_USER:-root}"
ADMIN_PASSWORD="${MYSQL_ADMIN_PASSWORD:-}"

SITE_NAME="${SM_SITE_NAME:-Smartest PHP8 Local}"
SITE_DIRECTORY="${SM_SITE_DIRECTORY:-SmartestPhp8Local}"
ADMIN_USERNAME="${SM_ADMIN_USERNAME:-admin}"
ADMIN_PASSWORD_PLAIN="${SM_ADMIN_PASSWORD:-password}"
ADMIN_FIRSTNAME="${SM_ADMIN_FIRSTNAME:-Local}"
ADMIN_LASTNAME="${SM_ADMIN_LASTNAME:-Admin}"
ADMIN_EMAIL="${SM_ADMIN_EMAIL:-admin@smartest.localhost}"
TEMPLATE="${SM_INITIAL_TEMPLATE:-smartest_php8_local.tpl}"

usage() {
  cat <<USAGE
Usage: Support/php8-local-bootstrap.sh [--files-only|--seed-db]

Creates local, ignored runtime files for the PHP 8 upgrade branch:
  Configuration/database.yml
  Public/.htaccess
  Sites/<site>/...

Modes:
  --files-only   create files/directories only (default)
  --seed-db      also create and seed a MySQL database

Useful environment variables:
  SM_LOCAL_HOSTNAME=${LOCAL_HOSTNAME}
  SM_DB_HOST=${DB_HOST}
  SM_DB_NAME=${DB_NAME}
  SM_DB_USER=${DB_USER}
  SM_DB_PASSWORD=********
  MYSQL_ADMIN_USER=${ADMIN_USER}
  MYSQL_ADMIN_PASSWORD=********
USAGE
}

sql_escape() {
  printf "%s" "$1" | sed "s/'/''/g"
}

random_webid() {
  php -r 'echo bin2hex(random_bytes(16));'
}

mysql_admin() {
  if [[ -n "$ADMIN_PASSWORD" ]]; then
    mysql -u "$ADMIN_USER" -p"$ADMIN_PASSWORD" "$@"
  else
    mysql -u "$ADMIN_USER" "$@"
  fi
}

mysql_app() {
  mysql -h "$DB_HOST" -u "$DB_USER" -p"$DB_PASSWORD" "$DB_NAME" "$@"
}

create_runtime_files() {
  mkdir -p "$ROOT_DIR/Configuration" "$ROOT_DIR/Public" "$ROOT_DIR/Sites/$SITE_DIRECTORY/Configuration"
  mkdir -p "$ROOT_DIR/Sites/$SITE_DIRECTORY/Presentation/Layouts" "$ROOT_DIR/Sites/$SITE_DIRECTORY/Presentation/Special"
  mkdir -p "$ROOT_DIR/Sites/$SITE_DIRECTORY/Library/Actions" "$ROOT_DIR/Sites/$SITE_DIRECTORY/Library/ObjectModel"

  cat >"$ROOT_DIR/Configuration/database.yml" <<YAML
# Database Connection Settings
# Generated by Support/php8-local-bootstrap.sh

---
SMARTEST:
  name: Main Database Configuration Parameters
  username: "${DB_USER}"
  password: "${DB_PASSWORD}"
  database: "${DB_NAME}"
  host: "${DB_HOST}"
  phptype: mysql
  class: SmartestMysql
YAML

  cat >"$ROOT_DIR/Public/.htaccess" <<HTACCESS
# .htaccess file for local Smartest PHP 8 work.
# Generated by Support/php8-local-bootstrap.sh.

Options +FollowSymLinks +ExecCGI

<IfModule mod_rewrite.c>
  RewriteEngine On
  RewriteBase ${REWRITE_BASE}

  RewriteCond %{REQUEST_FILENAME} !-d
  RewriteCond %{REQUEST_FILENAME} !-f
  RewriteRule ^(.*)$ index.php [QSA,L]

  RewriteCond %{REQUEST_FILENAME} -d
  RewriteCond %{REQUEST_URI} ^/Resources/
  RewriteRule ^(.*)$ index.php [QSA,L]

  ErrorDocument 404 ${REWRITE_BASE}Resources/System/Notices/NoApache404.html
</IfModule>
HTACCESS

  if [[ ! -f "$ROOT_DIR/Sites/$SITE_DIRECTORY/Configuration/site.yml" ]]; then
    : >"$ROOT_DIR/Sites/$SITE_DIRECTORY/Configuration/site.yml"
  fi

  if [[ ! -f "$ROOT_DIR/Sites/$SITE_DIRECTORY/Library/Actions/SiteActions.class.php" ]]; then
    cp "$ROOT_DIR/System/Base/ClassTemplates/SiteActions.class.php.txt" "$ROOT_DIR/Sites/$SITE_DIRECTORY/Library/Actions/SiteActions.class.php"
  fi

  if [[ -f "$ROOT_DIR/System/Install/Samples/default_user_profile_pic.jpg" ]]; then
    cp "$ROOT_DIR/System/Install/Samples/default_user_profile_pic.jpg" "$ROOT_DIR/Public/Resources/Images/default_user_profile_pic.jpg"
  fi

  if [[ ! -f "$ROOT_DIR/Presentation/Masters/$TEMPLATE" ]]; then
    sed "s/%DEFAULTTEMPLATENAME%\\.tpl/${TEMPLATE}/g" "$ROOT_DIR/System/Install/Samples/default.tpl" >"$ROOT_DIR/Presentation/Masters/$TEMPLATE"
  fi

  echo "Created local runtime files for http://${LOCAL_HOSTNAME}/"
}

seed_database() {
  if ! command -v mysql >/dev/null 2>&1; then
    echo "mysql client is not available on PATH." >&2
    exit 1
  fi

  mysql_admin <<SQL
CREATE DATABASE IF NOT EXISTS \`${DB_NAME}\` CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
CREATE USER IF NOT EXISTS '${DB_USER}'@'localhost' IDENTIFIED BY '${DB_PASSWORD}';
CREATE USER IF NOT EXISTS '${DB_USER}'@'127.0.0.1' IDENTIFIED BY '${DB_PASSWORD}';
GRANT ALL PRIVILEGES ON \`${DB_NAME}\`.* TO '${DB_USER}'@'localhost';
GRANT ALL PRIVILEGES ON \`${DB_NAME}\`.* TO '${DB_USER}'@'127.0.0.1';
FLUSH PRIVILEGES;
SQL

  mysql_app <"$ROOT_DIR/System/Install/SqlScripts/table_setup.sql"
  mysql_app <"$ROOT_DIR/System/Install/SqlScripts/user_tokens.sql"

  local temp_user_sql temp_site_sql now admin_password_hash
  temp_user_sql="$(mktemp)"
  temp_site_sql="$(mktemp)"
  now="$(date +%s)"
  admin_password_hash="$(printf "%s" "$ADMIN_PASSWORD_PLAIN" | php -r 'echo md5(stream_get_contents(STDIN));')"

  sed \
    -e "s/%USERNAME%/$(sql_escape "$ADMIN_USERNAME")/g" \
    -e "s/%PASSWORD%/${admin_password_hash}/g" \
    -e "s/%FIRSTNAME%/$(sql_escape "$ADMIN_FIRSTNAME")/g" \
    -e "s/%LASTNAME%/$(sql_escape "$ADMIN_LASTNAME")/g" \
    -e "s/%EMAIL%/$(sql_escape "$ADMIN_EMAIL")/g" \
    "$ROOT_DIR/System/Install/SqlScripts/create_user.sql.txt" >"$temp_user_sql"

  sed \
    -e "s/%NOW%/${now}/g" \
    -e "s/%TEMPLATE%/$(sql_escape "$TEMPLATE")/g" \
    -e "s/%EMAIL%/$(sql_escape "$ADMIN_EMAIL")/g" \
    -e "s/%SITENAME%/$(sql_escape "$SITE_NAME")/g" \
    -e "s/%DIRECTORYNAME%/$(sql_escape "$SITE_DIRECTORY")/g" \
    -e "s/%HOSTNAME%/$(sql_escape "$LOCAL_HOSTNAME")/g" \
    -e "s/%HOMEPAGEWEBID%/$(random_webid)/g" \
    -e "s/%ERRORPAGEWEBID%/$(random_webid)/g" \
    -e "s/%SEARCHPAGEWEBID%/$(random_webid)/g" \
    -e "s/%TAGPAGEWEBID%/$(random_webid)/g" \
    -e "s/%USERPAGEWEBID%/$(random_webid)/g" \
    "$ROOT_DIR/System/Install/SqlScripts/create_site.sql.txt" >"$temp_site_sql"

  mysql_app <"$temp_user_sql"
  mysql_app <"$temp_site_sql"
  rm -f "$temp_user_sql" "$temp_site_sql"

  echo "Seeded database ${DB_NAME}; local login is ${ADMIN_USERNAME} / ${ADMIN_PASSWORD_PLAIN}"
}

case "$MODE" in
  --files-only)
    create_runtime_files
    ;;
  --seed-db)
    create_runtime_files
    seed_database
    ;;
  -h|--help)
    usage
    ;;
  *)
    usage >&2
    exit 2
    ;;
esac
