{* Loaded when we are viewing a normal page (and thus most tabs refer to the page) *}
<ul class="tabset">
    {if $page_is_editable}<li{if $method == "editPage"} class="current"{/if}><a href="{$domain}websitemanager/editPage?page_id={$request_parameters.page_id}{if $request_parameters.item_id}&amp;item_id={$request_parameters.item_id}{/if}{if $request_parameters.from}&amp;from={$request_parameters.from}{/if}{if $request_parameters.author_id}&amp;author_id={$request_parameters.author_id}{/if}{if $request_parameters.search_query}&amp;search_query={$request_parameters.search_query}{/if}{if $request_parameters.tag}&amp;tag={$request_parameters.tag}{/if}">Page overview</a></li>{/if}
    {if $request_parameters.item_id && $item_is_editable}<li{if $method == "editItem"} class="current"{/if}><a href="{$domain}datamanager/editItem?item_id={$request_parameters.item_id}{if $request_parameters.page_id}&amp;page_id={$request_parameters.page_id}{/if}{if $request_parameters.from}&amp;from={$request_parameters.from}{/if}">Edit {$item._model.name|lower}</a></li>{/if}
    {if $page_is_editable}<li{if $method == "pageAssets"} class="current"{/if}><a href="{$domain}websitemanager/pageAssets?page_id={$request_parameters.page_id}{if $request_parameters.item_id}&amp;item_id={$request_parameters.item_id}{/if}{if $request_parameters.from}&amp;from={$request_parameters.from}{/if}{if $request_parameters.author_id}&amp;author_id={$request_parameters.author_id}{/if}{if $request_parameters.search_query}&amp;search_query={$request_parameters.search_query}{/if}{if $request_parameters.tag}&amp;tag={$request_parameters.tag}{/if}">Page elements</a></li>{/if}
    <li{if $method == "preview"} class="current"{/if}><a href="{$domain}websitemanager/preview?page_id={$request_parameters.page_id}{if $request_parameters.item_id}&amp;item_id={$request_parameters.item_id}{/if}{if $request_parameters.from}&amp;from={$request_parameters.from}{/if}{if $request_parameters.author_id}&amp;author_id={$request_parameters.author_id}{/if}{if $request_parameters.search_query}&amp;search_query={$request_parameters.search_query}{/if}{if $request_parameters.tag}&amp;tag={$request_parameters.tag}{/if}">Preview</a></li>
    {if !$is_special_page && !$request_parameters.author_id && !$request_parameters.search_query && !$request_parameters.tag}{if $page_is_editable}<li{if $method == "pageTags"} class="current"{/if}><a href="{if $request_parameters.item_id}{$domain}datamanager/itemTags?item_id={$request_parameters.item_id}{if $request_parameters.page_id}&amp;page_id={$request_parameters.page_id}{/if}{else}{$domain}websitemanager/pageTags?page_id={$request_parameters.page_id}{/if}{if $request_parameters.from}&amp;from={$request_parameters.from}{/if}">Tags</a></li>
    <li{if $method == "relatedContent"} class="current"{/if}><a href="{$domain}websitemanager/relatedContent?page_id={$request_parameters.page_id}{if $request_parameters.from}&amp;from={$request_parameters.from}{/if}">Related content</a></li>
    {if !$request_parameters.item_id}<li{if $method == "pageDownloads"} class="current"{/if}><a href="{$domain}websitemanager/pageDownloads?page_id={$request_parameters.page_id}">Downloads</a></li>{/if}
    <li{if $method == "authors"} class="current"{/if}><a href="{$domain}websitemanager/authors?page_id={$request_parameters.page_id}{if $request_parameters.from}&amp;from={$request_parameters.from}{/if}">Authors</a></li>{/if}
    {* <li{if $method == "pageComments"} class="current"{/if}><a href="{$domain}websitemanager/pageComments?page_id={$request_parameters.page_id}{if $request_parameters.from}&amp;from={$request_parameters.from}{/if}">Comments</a></li> *}{/if}
</ul>