<script language="javascript">

</script>

<div id="work-area">

<h3>Build a new model</h3>

{if $permissions_issue}
<div class="warning">
  <p>The following directories need to be writeable before you can save models.</p>
  <ul class="location-list">
{if !$site_om_dir_is_writable}<li><i class="fa fa-folder"></i> <code>{$site_om_dir}</code></li>{/if}
{if !$central_om_dir_is_writable}<li><i class="fa fa-folder"></i> <code>{$central_om_dir}</code></li>{/if}
{if !$cache_om_dir_is_writable}<li><i class="fa fa-folder"></i> <code>{$cache_om_dir}</code></li>{/if}
  </ul>
  {help id="desktop:permissions"}Tell me more{/help}
</div>
{/if}

<div class="special-box">Unsure about what "models" are? {help id="datamanager:models"}click here{/help} before you go any further.</div>

{if $has_modelkits}
<div class="special-box">
  <strong>Bundled model kits</strong>
  <ul class="options-list">
    {foreach from=$modelkits item="modelkit"}
    <li>
      <a href="{$domain}{$section}/executeItemClassKit?modelkit={$modelkit.id}" class="button">Install</a>
      <strong>{$modelkit.label}</strong>{if $modelkit.description} <span class="form-hint">{$modelkit.description}</span>{/if}
    </li>
    {/foreach}
  </ul>
</div>
{/if}

<form name="searchform" onsubmit="return liveSearchSubmit()" method="post" action="{$domain}{$section}/uploadItemClassKit" enctype="multipart/form-data">

<div class="edit-form-row">
  <div class="form-section-label">Upload model kit file</div>
  <input id="model-kit-file" type="file" name="model_kit_file" /><div class="form-hint">The file should have been generated by Smartest, and have a .modelKit file suffix.</div>
</div>

<input type="hidden" name="itemclass_role" value="freestanding" />

{if $central_om_dir_is_writable}
<div class="edit-form-row">
  <div class="form-section-label">Shared</div>
  <input id="shared" type="checkbox" name="itemclass_shared" value="1"{if !$site_om_dir_is_writable} checked="checked" disabled="disabled"{/if} /><label for="shared">Make this model available to all sites</label> {help id="desktop:multisite"}What does this mean?{/help}
  {if !$site_om_dir_is_writable}<div class="form-hint">This option is disabled because the directory <code>{$site_om_dir}</code> is not writable</div>{/if}
</div>
{elseif $site_om_dir_is_writable && !$central_om_dir_is_writable}
<div class="edit-form-row">
  <div class="form-section-label">Shared</div>
  <input id="shared" type="checkbox" name="itemclass_shared" value="1" disabled="disabled" /><label for="shared">Make this model available to all sites</label> {help id="desktop:multisite"}What does this mean?{/help}
  <div class="form-hint">This option is cannot be enabled because the directory <code>{$site_om_dir}</code> is not writable</div>
</div>
{/if}

{if $permissions_issue}
<div class="buttons-bar"><input type="button" onclick="cancelForm();" value="Cancel" /></div>
{else}
<div class="buttons-bar"><input type="button" onclick="cancelForm();" value="Cancel" /> <input type="submit" value="Install uploaded kit" /></div>
{/if}

</form>

</div>
