<script language="javascript">

</script>

<div id="work-area">

<h3>Build a new model</h3>

{if !$cache_om_dir_is_writable || ($site_om_dir_is_writable && $central_om_dir_is_writable)}
<div class="warning">
  <p>The following directories need to be writeable before you can save models.</p>
  <ul class="location-list">
{if !$site_om_dir_is_writable}<li><i class="fa fa-folder"></i> <code>{$site_om_dir}</code></li>{/if}
{if !$central_om_dir_is_writable}<li><i class="fa fa-folder"></i> <code>{$central_om_dir}</code></li>{/if}
{if !$cache_om_dir_is_writable}<li><i class="fa fa-folder"></i> <code>{$cache_om_dir}</code></li>{/if}
  </ul>
  {help id="desktop:permissions"}Tell me more{/help}
</div>
{/if}

<div class="special-box">Unsure about what "models" are? {help id="datamanager:models"}click here{/help} before you go any further.</div>

<form name="searchform" onsubmit="return liveSearchSubmit()" method="post" action="{$domain}{$section}/uploadItemClassKit" enctype="multipart/form-data">
    
<div class="edit-form-row">
  <div class="form-section-label">Upload model kit file</div>
  <input id="modelname" type="file" name="itemclass_name" /><div class="form-hint">The file should have been generated by Smartest, and have a .modelKit file suffix.</div>
</div>

<input type="hidden" name="itemclass_role" value="freestanding" />

{if $central_om_dir_is_writable}
<div class="edit-form-row">
  <div class="form-section-label">Shared</div>
  <input id="shared" type="checkbox" name="itemclass_shared" value="1"{if !$site_om_dir_is_writable} checked="checked" disabled="disabled"{/if} /><label for="shared">Make this model available to all sites</label> {help id="desktop:multisite"}What does this mean?{/help}
  {if !$site_om_dir_is_writable}<div class="form-hint">This option is disabled because the directory <code>{$site_om_dir}</code> is not writable</div>{/if}
</div>
{elseif $site_om_dir_is_writable && !$central_om_dir_is_writable}
<div class="edit-form-row">
  <div class="form-section-label">Shared</div>
  <input id="shared" type="checkbox" name="itemclass_shared" value="1" disabled="disabled" /><label for="shared">Make this model available to all sites</label> {help id="desktop:multisite"}What does this mean?{/help}
  <div class="form-hint">This option is cannot be enabled because the directory <code>{$site_om_dir}</code> is not writable</div>
</div>
{/if}

<div class="special-box">
  
  <input type="checkbox" name="create_meta_page" id="create-meta-page" value="1" onchange="toggleFormAreaVisibilityBasedOnCheckbox('create-meta-page', 'extra-form-options');"{if $cmp} checked="checked"{/if} /><label for="create-meta-page">Create meta-page now for this model</label>
  
  <div style="display:{if $cmp}block{else}none{/if}" id="extra-form-options">
    <div class="edit-form-row">
      <div class="form-section-label">Meta-page template</div>
      <select name="meta_page_template">
        {foreach from=$templates item="template"}
        <option value"{$template.url}">{$template.url}</option>
        {/foreach}
      </select>
    </div>
    <div class="edit-form-row">
      <div class="form-section-label">Meta-page parent</div>
      <select name="meta_page_parent">
        {foreach from=$pages item="page"}
          <option value="{$page.info.id}"{if $pageInfo.parent == $page.info.id} selected="selected"{/if}>+{section name="dashes" loop=$page.treeLevel}-{/section} {$page.info.title}</option>
        {/foreach}
      </select>
    </div>
  </div>
  
</div>

{if !$cache_om_dir_is_writable || ($site_om_dir_is_writable && $central_om_dir_is_writable)}
<div class="buttons-bar"><input type="button" onclick="cancelForm();" value="Cancel" /></div>
{else}
<div class="buttons-bar"><input type="submit" value="Next &gt;&gt;" /></div>
{/if}

</form>

</div>