ALTER TABLE `Items` ADD  `item_parent_id` INT( 11 ) NULL DEFAULT NULL AFTER  `item_public` ;
ALTER TABLE `Items` ADD  `item_order_index` INT( 11 ) NULL DEFAULT NULL AFTER  `item_language` ;
ALTER TABLE `ItemClasses` DROP  `itemclass_item_webid_format` ;
ALTER TABLE `Items` ADD  `item_createdat_ip` VARCHAR( 44 ) NOT NULL DEFAULT  '0.0.0.0' AFTER  `item_createdby_userid` ;
ALTER TABLE `Users` ADD  `user_answers_to_user_id` INT( 11 ) UNSIGNED NOT NULL ;
ALTER TABLE `UsersTokensLookup` ADD  `utlookup_object_id` INT( 11 ) NOT NULL AFTER  `utlookup_site_id` ;
ALTER TABLE `ManyToManyLookups` ADD  `mtmlookup_order_index_2` MEDIUMINT( 11 ) NOT NULL AFTER  `mtmlookup_order_index` ;
ALTER TABLE `ManyToManyLookups` ADD  `mtmlookup_order_index_3` MEDIUMINT( 11 ) NOT NULL AFTER  `mtmlookup_order_index_2` ;
ALTER TABLE `ManyToManyLookups` ADD  `mtmlookup_order_index_4` MEDIUMINT( 11 ) NOT NULL AFTER  `mtmlookup_order_index_3` ;
ALTER TABLE `Users` CHANGE  `user_website`  `user_website` VARCHAR( 255 ) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL DEFAULT  '';
ALTER TABLE `Users` ADD  `user_organization_name` VARCHAR( 128 ) NOT NULL AFTER  `user_website` ;
ALTER TABLE `Users` CHANGE  `password`  `password` VARCHAR( 255 ) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL DEFAULT  '';
ALTER TABLE `Users` CHANGE  `user_password_salt`  `user_password_salt` VARCHAR( 255 ) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL ;
ALTER TABLE `Sites` ADD  `site_primary_container_id` INT( 9 ) UNSIGNED NOT NULL ;
ALTER TABLE `Sites` ADD  `site_primary_text_placeholder_id` INT( 9 ) UNSIGNED NOT NULL ;
ALTER TABLE `Users` ADD  `user_activation_key` VARCHAR( 64 ) NOT NULL AFTER  `user_password_change_required` ;
ALTER TABLE `Pages` CHANGE `page_type` `page_type` VARCHAR(64) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL DEFAULT 'NORMAL';
ALTER TABLE `Pages` CHANGE `page_deleted` `page_deleted` VARCHAR(6) CHARACTER SET utf8 COLLATE utf8_unicode_ci NOT NULL DEFAULT 'FALSE';
ALTER TABLE `Pages` CHANGE `page_cache_interval` `page_cache_interval` VARCHAR(10) CHARACTER SET utf8 COLLATE utf8_unicode_ci NOT NULL DEFAULT 'PERMANENT';
ALTER TABLE `Pages` CHANGE `page_is_published` `page_is_published` VARCHAR(5) CHARACTER SET utf8 COLLATE utf8_unicode_ci NOT NULL DEFAULT 'FALSE';
ALTER TABLE `AssetIdentifiers` ADD  `assetidentifier_user_id` INT( 11 ) NULL DEFAULT NULL AFTER  `assetidentifier_item_id` ;
ALTER TABLE `AssetIdentifiers` ADD  `assetidentifier_tag_id` INT( 9 ) NULL DEFAULT NULL AFTER  `assetidentifier_user_id` ;
ALTER TABLE `Tags` ADD  `tag_description_text_asset_id` INT( 9 ) NOT NULL AFTER  `tag_label` ;
ALTER TABLE `Tags`ADD  `tag_icon_image_asset_id` INT( 9 ) NOT NULL AFTER  `tag_description_text_asset_id` ;
ALTER TABLE `Pages` DROP `page_pdf_version_asset_id`;
ALTER TABLE `Sets` ADD `set_info` TEXT CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT '' ;
ALTER TABLE `Pages` ADD `page_info` TEXT CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT '' ;
ALTER TABLE `AssetIdentifiers` ADD `assetidentifier_platform` VARCHAR(32) NOT NULL AFTER `assetidentifier_instance_name`;
ALTER TABLE `Assets` CHANGE `asset_variant_id` `asset_variant_name` VARCHAR(64) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL;
ALTER TABLE `Assets` ADD `asset_variant_label` VARCHAR(64) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL AFTER `asset_variant_name`;

UPDATE `Settings` SET `setting_value` = '744' WHERE `Settings`.`setting_type` ='SM_SETTINGTYPE_SYSTEM_META' AND `Settings`.`setting_name`='database_minimum_revision' LIMIT 1;
UPDATE `Settings` SET `setting_value` = '22' WHERE `Settings`.`setting_type` ='SM_SETTINGTYPE_SYSTEM_META' AND `Settings`.`setting_name`='database_version' LIMIT 1;